# Generated by Django 5.1.3 on 2024-12-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_perfume_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='price',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='size',
        ),
        migrations.CreateModel(
            name='PerfumeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('25 ml', '25 ml'), ('50 ml', '50 ml'), ('75 ml', '75 ml')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.perfume')),
            ],
        ),
    ]
