# Generated by Django 5.1.3 on 2024-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_perfume_price_remove_perfume_size_perfumesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, default=24.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='perfume',
            name='size',
            field=models.CharField(choices=[('25 ml', '25 ml'), ('50 ml', '50 ml'), ('75 ml', '75 ml')], default='25 ml', max_length=10),
        ),
        migrations.DeleteModel(
            name='PerfumeSize',
        ),
    ]
