# Generated by Django 5.1.3 on 2024-12-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_price',
            new_name='total_cart_price',
        ),
    ]
